title: "Life is Feudal: Extended"
description: "Life is Feudal: Your Own, LiFx, mod framework"
theme: just-the-docs

url: https://lif-x.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
plugins:
  - jekyll-default-layout
  
color_scheme: dark
